name: Build APK & EXE (placeholder workflow)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Android (gradle)
        run: |
          echo "This workflow is a placeholder. Add real build steps here."
      - name: Upload placeholder artifacts
        uses: actions/upload-artifact@v4
        with:
          name: placeholder-artifacts
          path: |
            scrcpy-android.apk
            scrcpy-win.exe
