name: Build and Release ZIP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP package
        run: |
          mkdir release
          cp scrcpy-android.apk release/ || true
          cp scrcpy-win.exe release/ || true
          zip -r scrcpy-lowlatency-gamecast.zip release

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: scrcpy-lowlatency-gamecast.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
